[package]
name = "ruthless_flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
timer = "0.2.0"
enumflags2 = "0.7.5"
